version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
      - mynetwork

  backend:
    image: haythambrahem/5se1-g3-devops
    container_name: backend
    restart: on-failure
    ports:
      - "7070:8089"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge