version: '3.1'

services:
  maddouridb:
    image: mysql:8.0
    container_name: maddouridb
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
      - mynetwork

  spring:
    image: maddouriahmed/5se1-g3-devops:latest
    container_name: spring
    restart: on-failure
    ports:
      - "7071:8089"
    depends_on:
      - maddouridb
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
