version: '3.1'
services:
  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
      - mynetwork

  pi:
    image: onsmaddouri/5se1-g3-devops:latest
    container_name: pi
    restart: on-failure
    ports:
      - "7070:8089"
    depends_on:
      - database
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
