version: '3.8'

services:
  appfront:
    build: .
    image: amalslimi/amalslimi-5se1-g3-devopsfront
    restart: on-failure
    container_name: frontend
    ports:
      - 4200:4200

  db:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped

    ports:
      - "3306:3306"  # Expose le port MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root  # Base de données par défaut

    networks:
      - mynetwork
    # Persistance des données
  backend:
    image: amalslimi/amalslimi-5se1-g3-devops:latest
    container_name: backend
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - db
    networks:
      - mynetwork


volumes:
  mysql_data:

networks:
  mynetwork:
          driver: bridge