##version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
      - mynetwork
  db_clone: # New service for additional instance
    image: mysql:5.7
    container_name: database_clone
    restart: unless-stopped
    ports:
      - "3307:3306"  # Different port to avoid conflict with the original
    volumes:
      - mysql_data_clone:/var/lib/mysql  # Separate volume
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
      - mynetwork

  backend:
    image: haythambrahem/5se1-g3-devops:latest
    container_name: backend
    restart: on-failure
    ports:
      - "7070:8089"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  mysql_data:
  mysql_data_clone:

networks:
  mynetwork:
    driver: bridge