version: '3.8'

services:
  appfront:
    build: .
    image: syrineahmed/syrineahmed-5se1-g3-devopsfront
    restart: unless-stopped
    container_name: frontend
    ports:
      - 4200:4200


  db:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped

    ports:
        - "3306:3306"
    volumes:
          - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root

    networks:
      - mynetwork

  backend:
    image: syrineahmed/syrineahmed-5se1-g3-devops:latest
    container_name: backend
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - db
    networks:
        - mynetwork


volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge