name: Notify Jenkins on Push

# Déclenche l'action sur chaque push dans la branche 'seifeddine'
on:
  push:
    branches:
      - seifeddine

jobs:
  notify-jenkins:
    runs-on: ubuntu-22.04
    steps:
    - name: Trigger Jenkins build
      run: |
        curl -X POST "http://http://192.168.110.130:8080/job/DevOps%20automation/buildWithParameters?token=seif-eddine-git-jenkins-workflow-notifier&branch=seifeddine" \
        --user "seif:1191b79da245175b29090225877cb0bc19"
